[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd apps/backend && pnpm build"]

[start]
cmd = "cd apps/backend && pnpm start"
